In [ ]:
#pip install transformers datasets torch scikit-learn

In [ ]:
import torch
print(torch.cuda.is_available())

True

# **Imports**

In [ ]:
import pandas as pd
import numpy as np
import re
import unicodedata
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from transformers import AutoTokenizer,AutoModelForSequenceClassification,Trainer,TrainingArguments

In [ ]:
train_path = "/content/drive/Shareddrives/NLP Task/trainV2.csv"

test_path = "/content/drive/Shareddrives/NLP Task/TestV2 - testV2.csv"

# **Load Dataset**

In [ ]:
df = pd.read_csv(train_path)

label_map = {"Non-Abusive": 0,"Abusive": 1,"abusive":1}

df["label"] = df["Class"].map(label_map)

In [ ]:
print(len(df))

3652

In [ ]:
df.isnull().sum()

Text     0
Class    0
label    0
dtype: int64

# **Preprocessing**

In [ ]:
def preprocess(text):
    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize("NFC", text)

    # Fix HTML entity
    text = text.replace("&#39;", "'")

    # Normalize spaces
    text = re.sub(r"\s+", " ", text).strip()

    # Lowercase English only
    text = re.sub(r"[A-Za-z]+", lambda m: m.group(0).lower(), text)

    return text

df["clean_text"] = df["Text"].apply(preprocess)

# **Train / Validation Split**

In [ ]:
train_texts,val_texts,train_labels,val_labels = train_test_split(df["clean_text"].tolist(),df["label"].tolist(),test_size=0.1,random_state=42,stratify=df["label"])

# **Load IndicBERT**

In [ ]:
model_name = "ai4bharat/IndicBERTv2-MLM-only"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name,num_labels=2)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/639 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/51.0 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.75M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ai4bharat/IndicBERTv2-MLM-only
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
bert.embeddings.position_ids               | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# **Tokenization**

In [ ]:
def tokenize(texts):
    return tokenizer(texts,padding=True,truncation=True,max_length=128)

train_encodings = tokenize(train_texts)
val_encodings = tokenize(val_texts)

# **Dataset Class**

In [ ]:
class TamilDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

train_dataset = TamilDataset(train_encodings, train_labels)
val_dataset = TamilDataset(val_encodings, val_labels)

# **Evaluation Metrics**

In [ ]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="binary")
    acc = accuracy_score(labels, preds)

    return {"accuracy": acc,"precision": precision,"recall": recall,"f1": f1}

# **Training Arguments**

In [ ]:
training_args = TrainingArguments(
    output_dir="./indicbert_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
    weight_decay=0.01,
    logging_dir="./logs",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

# **Trainer**

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    #tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

# **Train**

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=824, training_loss=0.37497075090130555, metrics={'train_runtime': 502.0252, 'train_samples_per_second': 26.182, 'train_steps_per_second': 1.641, 'total_flos': 864582927912960.0, 'train_loss': 0.37497075090130555, 'epoch': 4.0})

# **Evaluation**

In [ ]:
results = trainer.evaluate()
print(results)

{'eval_loss': 0.41827452182769775, 'eval_accuracy': 0.8333333333333334, 'eval_precision': 0.8222222222222222, 'eval_recall': 0.8361581920903954, 'eval_f1': 0.8291316526610645, 'eval_runtime': 2.6806, 'eval_samples_per_second': 136.535, 'eval_steps_per_second': 8.58, 'epoch': 4.0}

# **Test Prediction**

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(250000, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [ ]:
test_df = pd.read_csv(test_path)
test_df["clean_text"] = test_df["Text"].apply(preprocess)

test_encodings = tokenizer(
    test_df["clean_text"].tolist(),
    padding=True,
    truncation=True,
    max_length=128,
    return_tensors="pt"
)

# Move all tensors to device
test_encodings = {k: v.to(device) for k, v in test_encodings.items()}

model.eval()
with torch.no_grad():
    outputs = model(**test_encodings)
    preds = torch.argmax(outputs.logits, dim=1).tolist()

inv_label_map = {0: "Non-Abusive", 1: "Abusive",1: "abusive"}
test_df["prediction"] = [inv_label_map[p] for p in preds]

test_df[["Text","clean_text","prediction"]].to_csv("indicbert_submission.csv", index=False)

# **Validation Split Testing**

In [ ]:
val_predictions = trainer.predict(val_dataset)

y_true = val_labels
y_pred = val_predictions.predictions.argmax(axis=1)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(
    y_true,
    y_pred,
    target_names=["Non-Abusive", "Abusive"]
))

print(confusion_matrix(y_true, y_pred))

              precision    recall  f1-score   support

 Non-Abusive       0.84      0.83      0.84       189
     Abusive       0.82      0.84      0.83       177

    accuracy                           0.83       366
   macro avg       0.83      0.83      0.83       366
weighted avg       0.83      0.83      0.83       366

[[157  32]
 [ 29 148]]

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1:", f1)

Accuracy: 0.8333333333333334
Precision: 0.8222222222222222
Recall: 0.8361581920903954
F1: 0.8291316526610645

In [ ]:
print(val_dataset.labels)

[1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1]

In [ ]:
for i in range(len(val_texts)):
  print(val_labels[i],y_pred[i],val_texts[i])
#print(val_texts)

1 1 அடியே.... மானங்கெட்டவளே.... என்ன hair ku ..... இதையெல்லாம் எதுக்கு சொல்ற... கல்யாணம் பன்னா இது எல்லாம் நடக்கும்ன்னனு தெரியாதா சம்யுக்தா....என்னமோ ஓவரா அழுது நடிக்கிற
1 1 எது இவங்க ஜெயலலிதாவா அப்போ இரண்டு குஷ்பு கால் சூப்பு ரெடி ...........
0 0 ஹலோ ஷகிலா அம்மா இந்த லூசு கிட்ட பேசாதீங்க அப்புறம் உங்களுக்கு தான் பைத்தியம் ஆகிவிடுவார் please amma
0 0 ரொம்ப பொறுமையா பேசுறீங்க .u r appreciate mam
1 1 iva 22 வயசுலயே இப்படி னா இன்னும் என்னலாம் செய்ய காத்திருக்காளோ எம்மாடியோ
0 0 பணம் ,அழகு , நிறம் இருக்கிற பெண்கள் என்ன தவறு வேண்டுமானாலும் செய்யலாம் என்பதை இந்த பேட்டி மூலமாக சொல்றீங்க ஏன் திவ்யாவிடம் கேட்ட ஒரு கேள்வி கூட இரு பெண் பிள்ளைக்கு தாயான வனித்தவிடம் கேட்க வில்லை இப்படி தொடர்ந்து திருமணம் செய்து கொண்டே போனால் பெண் குழந்தையின் எதிர்காலம் என்ன ஆகும் என்று ஏன் கேக்கல வனித்தவை பார்த்தால் பயமா ? நன்றாக படித்த திவ்யாவை வீட்டு வேலைக்கு போக சொல்ற ஏன் சூரியா , இலக்கியவிடம் இதை சொல்லல இந்த பெண்ணை இவ்வளவு இழிவு படுத்தி இருக்க வேண்டாம் கொஞ்சம் அன்பா பண்பா அறிவுரை சொல்லி இருக்கலாம் சகோதரி சகிலா
0 0 மேலைநாடுகளில் இந்த உறவுகள் சாதாரண விஷயம். ஆனால் இங்கு தான் அசாதாரணமாக பார்க்கப்படுகிறது. காதலை சேர்த்து வைப்பது எத்தனை முக்கியமோ அதே போல தான் lesbion உறவுகளும்.
0 0 இது ஒரு பிரிரச்சனை இதுக்கு ஒரு ப்ரோக்ராம் பன்றாங்க பாரு து
1 1 எல்லாத்துக்கும் திறந்து காட்டிட்டு பத்தினி வேசம் போடுற. சிவப்பு விளக்கு வேட்பாளர்
0 0 நிறைய சோம்பேறிகளை யு டியூப் உண்டாக்குது. தடை செய்யலாம்
1 1 @venaphilipsuh664 உங்க ஆத்தா கூதி*ய நக்கிட்டு இருக்கேன்.. நாருது.. வந்து கழுவி விடுறா பு*ண்டா மவனே.. உங்க ஆத்தால எவ்ளோ ஓத்தா*லும் சலிக்கல..
0 0 சீனா, அமெரிக்க காரன்கள் social media, இணையதளம் மூலம் மற்ற நாட்டின் கலாச்சாரத்தை கெடுத்து, அழிக்கின்றனர் எல்லையில் துப்பாக்கி தூக்கி நாட்டைகாபாற்றிஎன்ன பிரையோசனம், இங்கே திறந்துகிடக்கிறது,
0 0 அட கருமம் புடிச்சவளுங்களா இதெல்லாம் ஒரு பொழப்பா நாட்டுல அவனவனுக்கு என்னென்ன பிரச்னை இருக்கு இதெல்லாம் ஒரு பொழப்பு அடத்தூ...
0 0 இவ்வளவு காசு கொடுத்து போன் வாங்க முடியும் சட்டிவிகேட் வாங்க முடியாது ம்ம் சற்று யோசிக்க வேண்டிய விஷயம் தான்
0 1 நாட்டுல எவ்வளவு பிரச்சினை இருக்கு இந்த இரண்டு லூசுகளையும் வச்சி செய்ரீங்களடா இந்த இரண்டு லூசையும் வர தேர்தலில் எடபாடிக்கும் ஸ்டாலினுக்கும் போட்டியா நிக்க சொல்லுங்கடா இவள்களுக்கும் நம்ம மக்கள் ஒட்டு போடும் ...
0 0 கார்த்தியை கண்டுபிடிச்சு திவ்யாட தரம்னு எந்த கட்சி தேர்தல் அறிக்கை விட்டு மக்களை திவ்யாவிடம் இருந்து காப்பாற்றுமோ அந்த கட்சி அமோக வெற்றி பெரும் 2021 தேர்தலில் முடியலடா சாமி
0 1 ஏய் மூதேவி..... இத சொல்லுறப்போ யாரேல்லாம் கத்தி சிரிச்சிங்க..
1 1 மேடம் இவளை சும்மா விடாதீங்க இவ பேசுறதெல்லாம் பொய் இந்த நாய் சம்பாதிக்க இவள் என்ன வேணும்மாலும் செய்வாள்
0 0 சுகந்தி பெரிய வில்லியாக இருப்பாங்களோ!!!! எல்லாம் வில்லத்தனம் காசு பணம் இருந்தா எவ்ளோ தப்பு பன்னலாம் அந்த பொன்னுக்கிட்ட காசு இருந்துருந்தா இப்போ அவங்க தான் நல்லவங்க என்ன கொடுமைடா
1 0 லச்சுமி தான் கார்த்தி யை வெச்சிருந்தா ஆனா இப்போ இல்ல...ஆனா கார்த்தி லச்சுமி யை வெச்சிருந்தான்....ஆமா
0 0 உன்னை படச்சதால கடவுளே கடவுளே குழப்பமாய் இருக்கிறார்
0 0 யாரெல்லாம் time வீணாக்கினிங்க இந்த விடீயோவை பார்த்து
1 1 தம்பி போய் நல்லவங்களை பேட்டிஎடு அவ சொல்வது அத்தனையும் பொய் தெரியாதா உனக்கு
1 0 லெஷ்மி மேடத்துக்கு வந்த சோதனையா ...சாவுங்கடி .. சனியன்களா
1 0 சகிலா மேடம் குக்வித்கோமாலில உங்கள‌ எனக்கு ரொம்ப பிடிக்கும் ‌நீங்க இந்த லுசுகிட்ட பேசாதிங்க‌ அத‌அப்படியே முஞ்சியில நாலு அப்புஅப்புங்க
0 0 மொத்தம் 50 க்கும் மேல... என்னது? பீப் சவுண்ட்.... யப்பா இதுக்கு பேரு நேர் கொண்ட பார்வை...
0 0 ஏம்மா நடுவர் அம்மா, நாட்ல எவ்வளவு பிரச்சனை, எதுக்கும்மா இந்த பஞ்சாயத்து உனக்கு? உங்களுக்கு துட்டு வேணும்னு நீங்க சம்பாதிக்க, இப்படி ஒரு நிகழ்ச்சி நடத்துறிங்க வெட்கமா இல்லையாம்மா? ஏம்மா நடுவரம்மா. நாட்ல இருக்க மக்கள் பிரச்சனைகளை பேசுமா. தீர்க்க முடியாத பிரச்சனையை எதற்கும்மா கூப்பிட்டு வச்சு கலபரம் பண்ணிகிட்டு இருக்க நடுவரம்மா
0 0 அடடா இந்த பொண்ணுங்க இந்த அளவுக்கு நாறி போய்ட்டாங்களே! கார்த்திக்குன்னு பேருவச்சிருக்கவனெல்லாம் 'கொரோனாவுக்கு ஜெ' (அய்யய்யோ) போட்டுட்டு மாஸ்க் போட்டுட்டு சுத்துங்கடா!
0 0 அந்த பொன்ன இப்படி டி ஆர் பிக்கு யூஸ் பன்னிட்டிங்களேடா போய் சிம்பிள் தான் சேனல் போய் பாருங்கடா அந்த பொன்னோட உண்மை முகம் தெரியும் ஏண்டா இப்படி எச்ச வேல பாக்குறீங்க
1 1 இந்த பைத்தியத்த செருப்பால அடிச்சு விரட்டுங்க மேடம்...
1 1 இவ தமிழ்நாட்ட என்னனு நினச்சுட்டு பேசறா மூதேவி. ஏ சுந்தரு உனக்கும் அறிவில்லையா? ஏண்டா உனக்காதான் பார்க்கிறோம். மரியாதையை காப்பாத்த பாருங்க.
0 0 இதை பிடிச்சு ஜெயில் ல போடுங்க சார்
1 1 தத்தோம் தகதிமிதோம் தோம்.. தோம்.. தகதிமி தகதிமிதோம் ... உடம்ப காட்டுனவ எல்லாம் அரசியலுக்கு... இவளுக்கு எல்லாம் நல்ல சாவுனு வரவே வராது....
0 0 அம்மா உங்களுக்கு தலை வலி வந்து அடுத்து அடுத்த எபிசோடு லீவ்
1 1 ஏண்டி நீயே ஒரு நடிகை உனக்கு மானம் வெட்கம் ரோசம் ஏதாவது இருக்கா. நீ ஜெயலலிதா அம்மாவா?
1 1 போடி பைத்தியக்காரி நடிப்பு‌‌ காரி ஓவரா நடிக்காத
1 1 இவ திங்கள் முதல் வெள்ளி வரை கிராமத்துல இருப்பா சனி ஞாயிறு ஹோட்டல் ரூம் போட்டு கண்டவன் கூட இருப்பா ஆதாரம் இவலோட யூடியூப் வீடியோ பார்த்தாலே தெரியும் தூ
1 1 பெண் எது சொன்னாலும் நம்பும் உலகம்.... இந்த பெண் பேசும் போதே திமிர் தெரிகிறது... பெண்ணை திருமணம் செய்து கொடுத்த பிறகு பெண்ணின் தாய் தந்தை அவர்கள் வாழ்க்கையில் தலையிடக்கூடாது
1 1 40 ஆண்டுகளுக்கு முன்பு இருந்து ரஜினி முதல், சிறிய நடிகர்கள் வரை எல்லோரும் சிகரட்டை பிடித்து நடித்து இருக்கிறார்கள். aunty இப்படி தொண்டை கிழிய ஏன் கழுதை போல கத்துகிறார். இவர் புதிய கட்சி ஆரம்பித்து , யாருமே கண்டுகொள்ளவில்லை. அதான்!! இவருக்கு இவரே வரலாறு std தெரியுமா?? என்று கேட்கிறார் aunty. உங்க வரலாறு தான் தெரியும்!! பா ம க கட்சியில் இருந்து வந்தவர் தானே!! அதான் இப்படி திடீர் சிகரெட் போராட்டம். நடிகர் விஜய் வேறு அரசியல் signal கொடுத்து இருக்கிறார். அதான் இந்த லெட்டர் பேடு கட்சி தலைவி இப்படி கோபத்தில் பேசுகிறார்
1 1 சூர்யா நீ பழைய அவிசரி தொழில் போய் விடு
0 0 இந்த you tube நாட்டையே நாசமாக்குது. பாத்ரூம் வரை றோட்டுக்கு வருது கறுமம்.
0 0 நாட்ல எவலோ பிரச்சினை இருக்கு உங்களுக்கு என்ன பிரச்சினை
1 1 இந்த பைத்தியகாரி இங்கேயும் வந்துட்டாளா? மூதேவி முண்டகலப்பி
1 0 சுகந்தி யும் சரியில்ல திவ்யாவும் சரியில்ல குடும்பப்பெண் நிகழ்ச்சி இருவரும் நல்லவர்கள் இல்ல இவர்கள் குடும்பத்தில் நல்லவர்கள் பெண்கொடுப்பார்களா பெண் எடுப்பார்களா இதை யோசித்தால் இருவரும் இப்படி இருப்பாரா
0 0 படிச்சு வேலை தேடி அலையும் நண்பர்கள் எல்லாம் கேட்டுகோங்க இந்த பொண்ணோட வருமானத்தை.. இதுங்கள ரோட்டுல விட்டு அடிச்சா மத்தவங்க திருந்திடுங்க.. சனியன்
0 0 இது behindwoods or divya or சுகந்தி or லக்ஷ்மி ராமகிருஷ்ணன் publicity ??
1 0 அட ச்சி த்து என்னடி பேசறீங்க ரெண்டு பேரும் உங்கள எல்லாம் ஓட விட்டு செருப்பை கழட்டி அடிக்கணும் ச்சி
1 1 எப்ப தப்பு பண்ணினாலும் தவறுதான் எத்தனை வருடம் ஆனாலும் பாலியல் தொழிலுக்கு ப்ரெய்ன் வாஷ் பண்ணுகிறாள்
0 0 ரமஷ்,மதுரை செல்வம் ,அழகுராஜா , மணிகண்டன் ,சிவா, பிரபு அப்புறம் நம்ம கார்த்தி அடேங்கப்பா சமூகம் பெரிய இடம் தான் போலஅடேய் எல்லா கார்த்தியும் ஓடிருங்கடா ஆரப்பாளையம் கார்த்தி அமெரிக்கா‌ கார்த்தி நீங்கள்லாம் தப்பிக்கவே முடியாதுடா
1 1 செருப்பால அடிச்சு பத்த வேண்டும் இது எல்லாம் என்ன ஜென்மங்கள் அடிங்க மேம்
0 0 சமயபுரம் மாரியம்மன் கோவில் எங்கே இருக்கு தஞ்சாவூர் காவல் நிலையம் எங்கே இருக்கு ??? என்ன கதை கதையா இருக்கு??? ரீல் சரி சூப்பர் ஸ்கிரிப்ட் சூப்பர்
1 0 டிக் டாக் ல சுகந்தி நிறைய ஆண்களுடன் பழக்கம் முதலில் சுகந்திக்கு எய்ட்ஸ் டெஸ்ட் எடுங்க மேடம்
1 1 பொன்னும், பொண்ணு கல்யாணம் பண்ணிக்கிட்டா ஆம்பளை இன்னா டி பண்றது.
1 1 இந்த ஓட்டுநர் பெண்ணுக்கு அகந்தை அதிகம்.தான் ஒரு புடுங்கி என்ற நினைப்பு.விளம்பரம் தேடும் சைக்கோ.
1 1 பின்னாடி செஞ்சாரு ஓகே.‌அது எப்படி 5 நாள் விடிக்காம இருக்க முடியும்?அங்கேயே‌ கழட்டி வெச்சுட்டாரோ? சட்னி கொண்டாந்த டாடி பக்கத்துல இருந்திருந்தா குசு நாத்தம் பொறுக்காம் இந்நேரம் போயி சேர்ந்திருக்க மாட்டாரு?! இவ அப்பனுக்கு 23 வருஷம் முன்னாடி fuse புடுங்கியிருந்தா இப்படியொரு புள்ள பொறந்தே இருக்காது.‌ சட்னி கொண்டுவந்தேன் மயிரு கொண்டுவந்தேன்னு அவ வாழ்க்கையே கெடுத்துட்டான் 'பாடு'. @ss mugic! promo sad music juper
0 0 ஸ்கிலா அம்மா நீங்க ஏன் இவங்கள பேட்டி எடுக்கிறிங்க போங்க மாம்
1 1 தூ தூ தூ தூ தூ தூ அன்பு தலைவி இன்று முதல் கக்கூஸ் கிழவி என்று அழைக்கப்படுவாள் நெக்ஸ்ட் மஸ்ரூம் போடுங்க
0 0 லஷ்மி ராமகிருஷ்ணன் அவர்களே உங்களிடம் ஒரு கேள்வி கேட்கிறேன் ஊரில் அது நடக்குது இது நடக்குதுன்னு சொல்றிங்களே அப்புறம் எதுக்கு இந்த இரண்டு முண்டங்களையும் இன்டர்வியூ எடுக்கிறீங்க ???
1 1 troll பண்றவங்க ல பார்த்தா இவளுக்கு பாவமா இருக்காம்... போடிங் வந்துட்டா... ஏய் நீ எப்பவும் troll பீஸ் தா..... மொத்தத்துல நாங்க விழுந்துட்டோம் ஆனாலும் மீசைல மண் ஒட்டல..
1 0 இவங்க ரெண்டு பேருமே தூக்கி உள்ள போடணும் இவங்கள விட்டா தமிழ்நாடோட கலாச்சாரம் அழிந்திடும்
1 1 இவ எல்லாம் ஒரு ஆளுனு பேசிட்டு இருகின்க இரண்டு பேரும் பொம்பளைங்க இல்ல பொறுக்கி நாய்க
1 1 உனக்கு அறிவு இல்ல உங்க ஆத்தா,அப்பனக்கு அறிவு இல்ல இத போயி கேஸ் போட்டு கோர்ட் ல சொல்ரதவிட்டு , வெட்கங்கெட்ட மீடியா கிட்ட சவடால் பேசிட்டு திரியிர நாடக கூத்தாடிகளுக்கு இதுதா சாதாரணமாயிருச்சே.தன்னோட பிரபலத்துக்காக தன்மானத்த , சுயமரியாதையு குடும்பத்தோட டைட்டானிக் கப்பல் ல ஏத்தி விட்ட கதையா இருக்கு sokerrrr fundaiingaaaa
0 0 சுகந்தி அக்கா செம்ம மாஸ் semma gethu akka semma gethu
0 0 கார்த்திக் ம்ம்ம்ம் மேடம் கார்த்திக் வேனும் ம்ம்ம் கார்த்திக் ௭ங்கடா இருக்க உணக்கு உசரம் மணிமேகலை காத்திருக்கா
1 1 ஒரு பெண்ணா இருந்து கொண்டு என்ன பேசுகிறோம் என்றே தெரியாமல் உளறிக் கொண்டு இருக்கிறாள். அவளை வைத்து கொண்டு கேள்வி கேட்டு கொண்டு கன்டெண்ட் கதையை உளறிக் கொண்டு இருக்கு லூசு. இது போன்று தரம் தாழ்ந்த விஷயங்களை காண்பிக்காதீர்கள்.
0 0 நல்லவேளை எங்க அப்பா எனக்கு யுவராஜ் என்று பெயர் வைத்தார்கள் தப்பித்தவறி கார்த்திக் நம் பெயரை வைத்திருந்தார் என்னுடைய விதி முடிஞ்சிருக்கும்,,
0 0 உதவி செய்தவர்களை மறந்த நீ உயரவே முடியாது.... நீ செய்த துரோகம் உன் வாழ்நாள் முழுவதும் தரத்தும்...
1 1 டேய் சத்தியமா சொல்ரேன் இவள பேட்டி எடுத்து அதுல வர காச வச்சு தான் நீ சாப்டனுமா அட பேதீல போவான்
1 1 கனிமொழியால் வேலைபோயிருச்சா நல்லது ஆமை புகுந்த வீடும் கனிமொழிபுகுந்த பஸ்சும் விளங்காது
1 1 தமிழகத்தில் கோட்டை கட்ட இங்கே குண்டு குளி இல்லையே குஷ்பு...நீங்க தான் இப்போது குண்டும் குழியுமா தமிழகத்தை நிசமாக்கிட்டீங்க
0 0 யாருடா அந்த கார்த்திக் எனக்கே உன்ன பாக்கணும் போல இருக்குடா
0 0 dhanush dialog::::::திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா திவ்யா
1 1 ஏண்டி சிறுக்கி மகளே இப்படி ஊரெல்லாம் கல்யாணம் பண்ணிக்கிட்டு ....ஊர்ல இருக்கிறவனோட சுத்துறியே எடக்கு முடக்க புள்ள பொறந்தா ..இன்சியலா யாரு பேர வெப்ப ...
1 1 அடியே பாம்பே துலுக்கச்சி...புருஷன் சொந்தபடம் எடுத்த பட்ட கடனை அடைக்க சங்கிட்ட விலை போயி ...கோணலாக ஒரு பொட்டு வச்சிகிட்டு....புருடா விட்டுகிட்டு அலயுறா....
1 1 சோபான்னா சுந்தரி உன்ன யாரு வச்சிருக்க... உனக்கு கோயில் கட்டுனு முட்டாள்கள் கூட இப்போ தெளிவா ஆயிட்டாங்க., இனிமே யார முட்டாள் ஆக்கபாக்குற., சேப்பாக் தொகுதில ஜெய்ச்சி கண்ணகி சிலை பக்கத்துல உனக்கு ஒரு சிலை வச்சிடலாம் னு பாக்குற but நீ கண்ணகி இல்லையே... so வாய்ப்பு இல்ல ராஜா
0 0 கண்டா வரச்சொல்லுங்க கார்த்தி கையோட கூட்டி வாருங்கள் திவ்யா காத்திருக்காங்க
1 1 இந்த லூச ஜெயில்ல போடுங்க மெண்டல் ஷீலா ஒரு நம்பர் one லூசு
0 1 ஏம்மா நீங்க செருப்பு போடாமலே ஒக்காந்து இருக்கீங்க
0 0 msc micro-biology படிச்சிருக்கியா....நீ behave பண்றதல்லாம் பாக்கறப்போ படிச்ச பொண்ணு மாறி இல்லையே....
1 1 பரதேசி இந்த கிழட்டு தேவிடியாளை பேட்டி எடுக்கிற உண்ணை செருப்பாலே அடிக்கனும்
0 0 இதே போல் வணக்கமுங்கோ ஷீலா வை ஒரு interview எடுங்க
0 0 கார்தி என்னும் பெயரில் திவ்யாவை பேக் ஐ.டி யில் காதலித்த உங்கள் சாக்லேட் பாய் வேல்ராஜ்
1 0 வற வற தோப்பு ரொம்ப பெருசாகிட்டே போகுதே...தண்ணி ரொம்ப பாய்தோ....
1 0 டைம் டைம் தெரியாதா ஆனால் கார்த்தி மட்டும் தெரியும் உனக்கு திவ்யா மூஞ்சி
1 1 குஷ்பு நல்லா மார்பை காட்டி ஆடுவாள் அரசியலுக்கும் அவருக்கும் என்ன சம்பந்தம்
1 1 அவள செருப்பால அடிச்சு வெளியில அனுப்புங்க மேடம் பெண்கள் வர்க்கத்துக்கு அவ ஒரு அசிங்கம்
0 0 இவளோட 1st பையன் illegalla பொறந்தது. அப்பா பேரு தெரியாத பையன். பாவம் பாலா விநாயகம். சிக்கா மாதிரி யாரோ பெத்த பையனுக்கு அப்பா ஆகிட்டான்
0 0 இத எப்படி மா பொருத்து உட்கார்ந்து இருக்கீங்க
1 1 பொண்ணுக சொன்ன எல்லாத்தையும் நம்புவாங்க பசங்க சொன்ன ஒரு பயலும் நம்பமாட்டானுக ஒரு பொண்ணு நினைச்சா ஒரு பயன்ன ஆக்கவும் முடியும் அளிக்கவும் முடியும் அத தான் இவ பண்ணிட்டு இருக்கா பசங்க யாரும் இப்படிலாம் பண்ண மா உருட்டு மா நி நல்லா
0 1 என்னங்கடா இவ்ளோ நேரம் நல்லாத்தானேயா பேசிட்டு இருந்தா.
0 0 ஷகிலா மேடம் சூப்பர் மக்கள் மனசுல பாரம் இப்பதான் குறைஞ்சிருக்கு நாங்க கேட்கணும்னு நினைச்சேன் எல்லாம் கேள்வி நீங்களே கேட்டீங்க நன்றி
0 0 இரண்டு பேரும் சேர்ந்து லக்ஷ்மி மேடம் ஐ வறுத்து எடுக்கும் program போல இருக்கு........ இது என் கருத்து.... திவ்யா and சுகந்தி ...... யார்ப்ப நிஜமான culprit????
0 0 இத பார்த்தால் எதிர் காலத்துல வரும் குழந்தைகள் இதே மாதிரி செய்து வாழ்க்கை கெட வாய்ப்பு உள்ளது,,இந்த நாசமா போன you tube னால இந்த கண்றாவியெல்லாம் பார்க்க வேண்டியதா இருக்கு,,தூ ,
0 0 இதிலிருந்து என்ன தெரியுது ரண்டுபேரும் தேவிடியானு தெரியுது
0 0 தமிழ் நாடு மக்களுக்கு திவ்யா கிடச்ச வரம் நல்ல சிரிப்பு காட்ரிங்க
1 1 நாட்டுல எவ்வளவோ பிரச்சனை இருக்கு தாயோழிங்க குடும்ப கதைய எடுத்து ஓட்டிட்டு இருக்கானுங்க
1 0 இரண்டும் ஓரே ஏர் தான் நாட்டுக்கு இது கேடு
0 1 இவளுகளுக்கு பஞ்சாயத்து பண்ண ஒரு ஆளு துக்கி போட்டு midhichu அனுப்புங்க பஞ்சாயத்து தலைவரே
0 0 மடம் தலைஎலுத்து. இதல்லாம் பாக்கனும் 40:55 40:59 இதல்லாம் கேக்கனுமுன்னு
1 1 ஒன்னோட சைசுக்கு நீயே ஒரு நாளக்கி 5கிலோ ஆய் போவ ஒனக்கு இந்த சைஸ் போதுமா?
0 0 டேய் behindwoods air சத்தியமா என்னால சிரிப்ப அடக்க முடியாலடா டேய்
0 0 அப்புறம் என்ன மயிருக்கு, பேச வந்த, சகிலா அக்கா sama
0 0 சகிலா மேடம் நன்றி நன்றி இது மாதிரி சில நபர்களை தேடி எங்களுக்கு தெரிய படுத்தியது நன்றி இவங்க மாதிரி ஆட்கள் வாழ்வது இந்த பூமிக்கு கடும் எதிர்ப்பு
0 1 டே கலாட்டா என்னடா இது இதுக்கு நீ சிக்கா கிட்ட எடுபிடி வேலைக்கு போலாம்டா
1 1 ஆபாசமாக பேசுவதை நிறுத்துங்கள் சாதனா அட்வைஸ் சொல்லவில்லை இது என் கருத்து...
0 0 நல்ல நாக்கை புடுங்குற மாறி கேளுங்க மேடம்
1 1 ஓசி கனிமொழியால் சர்மிளாவின் வேலை பறி போனது திராவிட மாடெல் ஆட்சி
0 0 இந்த மாதிரி வீடியோ போட்டா நா அடிப்பேன் செருப்பால
1 1 இவ வாய் திறந்த பொய். இவ வண்டவாளம் வெளியே வந்த உடன பச்சையா பொய் சொல்லுறா
1 0 ரஜினி mind வாய்ஸ் ஏன்டி நான் உன்னை கூப்பிட்டது என் வீட்டு கக்கூஸ் கழுவ
1 1 சுகந்தி காம படத்திற்கு ஏற்றார் போல் இருக்கிறாள்
0 0 எவ்ளோ நல்லவர்கள் திறமையானவர்கள் இருக்கிறார்கள்... அவர்களை பேட்டி எடுக்காம... இதுங்கள எதுக்கு பேட்டி எடுத்து... உங்கள் மரியாதைய கெடுத்துக்கரிங்க....
1 1 உன்னோட ஆசைக்காக பெத்தவங்கள கஷ்ட படுத்தாத நீதான் ரொம்ப கஷ்டப்படுவமா
0 0 முன்பெல்லாம் பெண்கள் குழாயடியில் சண்டை இடுவார்கள் இப்போது டிக்டாக்கில். வாழ்க டெக்னாலஜி
0 0 சுகந்தி ஆர்மி மதுரை மாவட்டம் உறுப்பினர் சேர்க்கை நடைபெறுகிறது.........
0 0 சுகந்தி ஆர்மி மதுரை மாவட்டம் உறுப்பினர் சேர்க்கை நடைபெறுகிறது.........
0 0 உண்மைய சொல்றேமக்கா, நானும் 3 தடவை இந்த பதிவு பாத்துவிட்டேன் ஒன்னுமே புரியலப்பா கருமம் கன்றாவி
0 0 ஐயோ ஏன் இந்த நிலை அழாதே வாழ வழி தேடி ஒரு ஆண் மகனை தேடி கொள்க
0 0 திவ்யா டிக்டாக்கிற்குள் வந்தால் கார்த்தியை தன் காதலனாக நினைத்தாள் கடைசியில் கார்த்தியின் காதலியாகவே மாறிவிட்டாள்
1 0 ரஜினி mind வாய்ஸ் ஏன்டி நான் உன்னை கூப்பிட்டது என் வீட்டு கக்கூஸ் கழுவ
0 1 டீப்பா இருக்கணும்னு சொன்னானா இந்த அம்மா டீப்பா கேக்குது
0 0 டேய் யப்பா கார்த்தி வந்துருடா... எங்களால முடியல.. இது மாதிரி வீடியோ பாத்து தமிழ்நாடே சுடுகாடு ஆகிடும் போல.. தயவுசெய்து வந்துருடா
0 1 உன் வாய்ஸ் கரகாட்டம் பரமேஸ்வரி வாய்ஸ் ஒரே மாதிரி இருக்கு எனக்கு மட்டும்தான் அப்படி இருக்கோ
1 1 இவல ஒரு ஆளு இவளுக்கு ஒரு பேட்டி
0 0 என்னடா இது தஞ்சாவூருக்கு வந்த சோதனை சேத்தாண்டா கார்த்தி வெக்காளி
0 0 நேர் கொண்ட பார்வைய மாத்திட்டு கலக்க போவது யாரு நு வச்சி கோன்க
0 0 ஷகிலா மேடம் இந்த வீடியோவை பார்த்து மக்கள் இனி நல்லது கெட்டது தெரிஞ்சுக்கிட்டோம் நன்றி மேடம்
1 0 ஆகமொத்தம் மக்கள முட்டாள்ன்னு நெனச்சிருக்காங்க செருப்பை கழட்டி அடிக்கணும்
1 1 ஆணும் பெண்ணும் பாசத்துக்கு அடிமை ஆயிட்டாங்க ஆனா அந்தப் பெண்ணை அந்தப் பெண் நல்லா ஏமாற்றி இருக்கா அது மட்டும் நல்லா தெரியுது ஆணா பெண்ணோ பெண்ணோ வாழ்வது பூமிக்கு அடுக்காது
0 0 லட்சுமி அக்கா,,,,48 வாட்டி சொல்றாங்க,,,, இப்போ என்ன வேணும்,,, இப்போ என்ன வேணும் ,,,,
1 1 தேவடியாவிடம் பேட்டி எடுக்குற தேவடியா புள்ளைங்களா திருந்தவேமாட்டீங்களாடா..??
0 0 அடப்பாவிகளா இதெல்லாம் ஒரு பொழப்பா டா நாட்டிலே இருக்கிற பிரச்சினைக்கும் தீர்வுகாண முடியாது சுத்துறாங்க
0 0 சுகந்தி நீ கொழ மாஸ் i love u சுகந்தி
1 0 @pradeepking431 அவளுக்கு கல்யாணம் ஆகுறதே சந்தேகம் தான் அப்பறம் எப்படி இதெல்லாம்
0 1 காரி துப்பிட்டு போறவங்க எல்லாம் துப்பிட்டு போங்க
1 1 எங்கள பாத்தா பைத்தியம் மாதிரி தெரியுதா உனக்கு கையில மாட்ன கொலபண்ணிடுவேன்
0 0 இந்த program ah நிப்பாட்டுங்க தயவுசெய்து முண்டைகளா மூதேவீ முண்டைகளை கெடுக்கிறது இந்த program தான்
0 0 இன்னேரம் அந்த கார்த்தி gazette ல பேர மாத்திட்டு கேரளாவுக்குப் போய் தலைமறைவாயிருப்பான்
1 1 கம்பிய பழுக்க வச்சு சூத்துல வைங்க சார்
1 0 ப்ப்பா... வெற லெவல் யா அந்த சுகந்தி ஆண்டி... சுகந்தி ஆண்டிக்காக பார்க்க வந்தவங்க கை தூக்குங்க....
1 1 சனியனே அப்போ என் இன்னும் நீ கர்ப்பமாகல... பித்தலாட்டம்
1 1 அது என்னப்பா வாய் இரண்டு பக்கமா வெள்ளையா இருக்கு
1 1 இந்த மூணும் ஒரே கேஸ்தான். பெண்களின் அவமானச் சின்னங்கள் இவைகள். தூக்கிட்டு போயி அறுக்கனும் வெட்கம் கெட்ட பன்னிங்க.
1 0 கார்த்தி எங்கிருந்தாலும் உடனே சென்னை வரவும் உனக்காக அன்பான காதலி திவ்யா மற்றும் ஐட்டம் சுகந்தி காத்திருக்கிறார்கள். உடனே வந்து சேர்ந்து விடு.
1 1 இவ கிளாமர் பாத்து உன்ன தள்ளு நங்கா .கிருக்கு குதி ‌.பெண் கல இவ இலிவு படுத்துரா ‌.ஜடம்
1 1 இவள் கண்டிப்பாக தினமும் சோறு சாப்பிட மாட்டாள் என்பது இதன் மூலம் தெரிகிறது
0 0 கார்த்தியை கத்தி முனையில் கடத்தி வைத்து திவ்யாவை அருவாமனை எடுக்க வைக்கும் வேல்ராஜ்
0 0 இந்த கார்த்தி போட்டோவ பாருங்க கொஞ்சம் போட்டோ அனுப்பி விடுங்க ப்ளீஸ்
0 0 கார்த்தியை வர சொல்லுக..., அந்த கண்டார** கார்த்தியை வர சொல்லுக...
0 0 e எல்லா youtuber களும் பணம் சம்பாதிக்க தான் வீடியோ போடுகிறார்கள். சினிமா வுக்கு இருப்பது போல் youtube க்கும் censor board அமைத்து கண்காணிக்க வேண்டும். அப்போது தான் இளைய சமுதாயம் ஒழுங்கா இருக்கும். .
0 0 கார்த்திய கண்டுபிடிச்சி கொண்டுவருங்க... கையோட இழுத்துவருங்க......கார்த்தி எங்கய்யா இருக்கா... திவ்யா பொழப்பு பொசுக்ண்டுபோயிடுச்சி...
1 1 இதையெல்லாம் கூட்டு வச்சி பேசுறதே எவ்வளவு கேவலத்திலும் கேவலம் தெரியுமா...செருப்படி குடுத்து ஜெயில்ல புடிச்சி போட வேண்டியத எல்லாம் மனசாட்சியோ வெக்கமோ இல்லாம கூட்டிட்டு வந்து பேட்டி எடுக்குறிங்களே வெளங்குவிங்களாடா நீங்க....
0 0 நவரச நாயகன் கார்த்திக் அவர்களும் திவ்யாவுக்கு பயந்து தலைமறைவு .அதிர்ச்சயில் உலக நாட்டு தலைவர்கள். குடும்பத்தினர் உச்சநீதி மன்றத்தில் ஆட்கொணர்வு மனு
0 1 10 குழந்தைகள் அழிச்சிட்டு பத்தினி மாதிரி உருட்டி.கொன்டிருக்கிறாள் இவள் அவ்வளவு நல்லவள் மாதிரி
0 0 மேடம் எனக்கு ஒன்னு மட்டும் புரியல... திருச்சி சாதனா விடம் எப்படி பேசுனீங்க இனியா விடம் எப்படி பேசுனீங்க .. அந்த சினிமா நடிகைகளை தவறாக பேசும்... நாயிடம் எப்படி பேசுனீங்க இவளிடம் நீங்க இப்படி பேசுவது சரியா???... இவளுக்கு குடும்பம் இல்லை ஆனா சாதனாவுக்கு குடும்பம் இருக்கு.. அவள் பேசியதை ரசித்து கேட்டிங்க .. இவளுக்கு அழகு இல்லை யா...? வேசியாக போனால் என்ன..? அவளுக்கு என்ன செய்ய முடியுமோ அதை செய்து பணம் பார்க்கிறாள் இதில் உங்களுக்கு என்ன மேடம் ... உங்க தகுதிக்கு நீங்க பேசுங்க அவளில் தகுதிக்கு அவள் இருக்கட்டும் இத்தனை நாள் நீங்க ரொம்ப நல்லவர்கள் என்று நினைத்தேன் நீங்களும்... அழகையும்.. பகட்டானா... வேஷம் போடும் நபர்களுக்கு பேசுவது நல்லாவே இல்ல திட்டுங்கள் ஆனா... எல்லோரையும் ஒரே மாதிரி.. பேசுங்க
1 1 (மதுவன்டி )சூடு சொரனை எதுவும் கிடையாது?போதையில் பேசுறாள். நேத்து அடிச்ச போதையில் பேசுறாள். நல்லா செய்ரார் போல?
0 0 கடைசி வர எது உண்மை...! எது பொய் என்னு தெரியாதவங்க இருக்கீங்களா...
0 0 கொரானா விரட்டி அடிக்கப்பட்டது இவர்களால்தான் என்பது கூட தெரியாமல் அரசாங்கம் அவர்கள் எடுத்த நடவடிக்கையால் தான் கொரானா குறைந்தது என்று பீற்றிக் கொள்கிறார்கள்.
0 0 idha brikya இதைவிட கேவலமான பொண்ணு அந்த காசு சம்பாதிக்க எவ்வளவு எக்ஸ்ட்ரீம் லெவலுக்கும் போறாங்க
1 1 சின்மயி மனநலம் சரியில்லாத காரணத்தால் அப்படி பேசிட்டாங்க.....
1 1 இந்த அம்மாவையும் ஒரு நல்ல மனநல மருத்துவரை அணுக ஆலோசனை கொடுங்கள். இவங்க ஒரு vp ( விளம்பர பைத்தியம்)
1 1 இந்த முண்ட உங்களுக்கு பேபி யாடா கிழட்டு முண்டம்
0 0 ஒரு லட்சம் வாங்கல.......ரண்டு லட்சம் வாங்கி ருக்குற..
0 0 இரண்டுபேரையும் அவர்கள் சொந்த ஊரில் கட்டி வைச்சு அந்த ஊர் மக்களை தண்டிக்க சொல்லுங்க.,.அப்ப தான்ஊர் நல்ல இருக்கும். பஞ்சாயத்தும் நல்ல நடக்கும். போலிஸ் மற்றும் லட்சுமிமேடமுக்கும் வேலை இருக்காது. காவல்துறைக்கு இதைவிட பொதுமக்கள் முக்கீயம்.
0 0 சகோதரி ஷகீலா எவ்வளவு டேலணட் உங்களுக்கு நீங்கள் அனுகும் முறைக்காகதான் பார்க்கிறேன்....நடிகைக்கு அப்பாற்பட்ட அற்புத திறமை உங்களிடம்...பழைய நடிகைகளிடம் இன்றும் பேசுகிறேன் என்பதில் பெருமை அவர்களும் மதிக்கின்றனர்
1 1 எடி தேவடியா உனக்கேஎலம் அம்பலையே கன்னுக்கு தேரியதா தேவடிய மவேலே
0 0 30.00 la lakshmi உலகத்தில் அவ்லோ பிரச்சினை போகுதுல... அப்ப என்ன மயித்துக்கு கூட்டிட்டு வந்து trp க்கு பண்றீங்க..... பெரிய பருப்பு மாதிரி பேசுறீங்க.....
0 0 அப்ரம் epdi antha vasanth 5பவுன் la chain போட்டாரு.....எல்லாத்துக்கும் karanam vasanth
0 0 ஆரப்பாளையம் மதுரை ரெண்டுமே ஒண்ணு தானே ..யேன் பிறிக்கிற
1 1 அஞ்சு ரூபா ஐட்டத்த கூட்டிட்டு வந்து பேட்டி எடுக்குறீங்க தமிழ்நாடு உருப்படாது போல
1 1 இந்த ரெண்டு தேவிடியாவையும் செருப்பால அடிச்சி விறட்டுங்க மேடம்
1 1 பைத்தியம் திவ்யா செத்து போ சுகந்தி நீ செய்யுற வேலை தப்பா இருக்கு திருத்திக்கோ

In [ ]:
print(len(val_labels))

366

In [ ]:
print(len(train_texts))

3286

In [ ]:
print(len(df))

3652